Refactor tags to sqlite + drizzle
huang0h/cs4530-project pull request #10
Opened 2024-10-16 22:01 UTC by ninest

2024-10-18 20:01 UTC, huang0h requested changes

2024-10-18 20:01 UTC, huang0h commented on server/models/application.ts
> +    console.log(tagsList);
can we remove this console log to keep the console clean?

2024-10-18 20:04 UTC, huang0h approved these changes
:shipit:

2024-10-25 20:50 UTC, rkaushik2 approved these changes
looks good

2024-10-25 20:50 UTC, merged